### ISSUE TITLE
"show" class might not be needed

### ISSUE THREAD

**Issue by john-terenzio** [laharrell20XX/logan-harrell-web-rental-agency#1]
https://github.com/laharrell20XX/logan-harrell-web-rental-agency/blob/a76944866a1075d0f3378f8babf934309f5e5674/js/javascript.js#L54

I've seen a lot of people just use `hide` class to hide and if `hide` is not there then show (instead of having a `show`) class. This might simplify your code.

**Comment by laharrell20XX** [comment]
So I tried removing the show class like you suggested, but then my dropdown menus started showing some weird behavior.  In the interest of time, I just decided to leave the page as it was.
